src/Entity/Sliders.php
<?php

namespace App\Entity;

use App\Repository\SlidersRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SlidersRepository::class)]
class Sliders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $button_text = null;

    #[ORM\Column(length: 255)]
    private ?string $button_link = null;

    #[ORM\Column(length: 255)]
    private ?string $imageUrl = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $udpated_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    public function __construct () {
        $this->setCreatedAt( new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getButtonText(): ?string
    {
        return $this->button_text;
    }

    public function setButtonText(string $button_text): static
    {
        $this->button_text = $button_text;

        return $this;
    }

    public function getButtonLink(): ?string
    {
        return $this->button_link;
    }

    public function setButtonLink(string $button_link): static
    {
        $this->button_link = $button_link;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->imageUrl;
    }

    public function setImageUrl(string $imageUrl): static
    {
        $this->imageUrl = $imageUrl;

        return $this;
    }

    public function getUdpatedAt(): ?\DateTimeImmutable
    {
        return $this->udpated_at;
    }

    public function setUdpatedAt(?\DateTimeImmutable $udpated_at): static
    {
        $this->udpated_at = $udpated_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\ProductRepository;
use App\Repository\PageRepository;
use App\Repository\CollectionRepository;
use App\Repository\CategoryRepository;
use App\Repository\SlidersRepository;
use App\Repository\SettingRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{

    private $repoProduct;

    public function __construct(ProductRepository $repoProduct){
        $this->repoProduct = $repoProduct;
    }

    #[Route('/', name: 'app_home')]
    public function index(
        SettingRepository $settingRepo, 
        SlidersRepository $sliderRepo, 
        CollectionRepository $collectionRepo, 
        CategoryRepository $categoryRepo, 
        PageRepository $pageRepo, 
        Request $request): Response
    {
        $session = $request->getSession();

        $data = $settingRepo->findAll();
        $session->set("setting", $data[0]);

        $sliders = $sliderRepo->findAll();

        $collections = $collectionRepo->findBy(['isMega' => false]);
        $megaCollections = $collectionRepo->findBy(['isMega' => true]);
        

        $headerPages = $pageRepo->findBy(['isHead' =>true]);
        $footerPages = $pageRepo->findBy(['isFoot' =>true]);
        $session->set("headerPages", $headerPages);
        $session->set("footerPages", $footerPages);

        $categories = $categoryRepo->findBy(['isMega' => true]);
        $session->set("categories", $categories);
        $session->set("megaCollections", $megaCollections);
        
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'sliders' => $sliders,
            'collections' => $collections,
            'productsBestSeller' => $this->repoProduct->findby(['isBestSeller' => true]),
            'productsNewArrival' => $this->repoProduct->findBy(['isNewArrival' => true]),
            'productsFeatured' => $this->repoProduct->findBy(['isFeatured' => true]),
            'productsSpecialOffer' => $this->repoProduct->findBy(['isSpecialOffer' => true]),
        ]);
    }

    #[Route('/product/{slug}', name: 'app_product_by_slug')]
    public function showProduct(string $slug)
    {
        $product = $this->repoProduct->findOneBy(['slug'=>$slug]);

        if(!$product){
            // error
            return $this->redirectToRoute('app_error');
        }

        return $this->render('product/show_product_by_slug.html.twig', [
            'product'=> $product
        ]);


    }

    #[Route('/product/get/{id}', name: 'app_product_by_id')]
    public function getProductById(string $id)
    {
        $product = $this->repoProduct->findOneBy(['id'=>$id]);

        if(!$product){
            // error
            return $this->json('false');
        }

        return $this->json([
            'id' =>$product->getId(),
            'name' =>$product->getName(),
            'imageUrls' =>$product->getImageUrls(),
            'soldePrice' =>$product->getSoldePrice(),
            'regularPrice' =>$product->getRegularPrice(),
        ]);


    }

    #[Route('/error', name: 'app_error')]
    public function errorPage()
    {
        return $this->render('page/not-fount.html.twig', [
            'controller_name' => 'PageController'
        ]);

    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}JStore - HomePage{% endblock %}

{% block body %}

<div  class="banner_section slide_medium shop_banner_slider staggered-animation-wrap">
    <div  id="carouselExampleControls" data-bs-ride="carousel"
        class="carousel slide carousel-fade light_arrow">
        <div  class="carousel-inner">
            {% for slide in sliders %}
                <div  class="carousel-item {{loop.index < 2 ? 'active' : ''}} background_bg"
                
                    data-img-src="/assets/images/sliders/{{slide.imageUrl}}"
                    style="background-image: url('/assets/images/sliders/{{slide.imageUrl}}');">
                    <div  class="banner_slide_content">
                        <div  class="container">
                            <div  class="row">
                                <div  class="col-lg-7 col-9">
                                    <div  class="banner_content overflow-hidden">
                                        <h5  data-animation="slideInLeft"
                                            data-animation-delay="0.5s"
                                            class="mb-3 staggered-animation font-weight-light animated slideInLeft"
                                            style="animation-delay: 0.5s; opacity: 1;">{{slide.description}}</h5>
                                        <h2  data-animation="slideInLeft"
                                            data-animation-delay="1s" class="staggered-animation animated slideInLeft"
                                            style="animation-delay: 1s; opacity: 1;">{{slide.title}}</h2><a
                                            data-animation="slideInLeft"
                                            data-animation-delay="1.5s"
                                            target="_blank"
                                            class="btn btn-fill-out rounded-0 staggered-animation text-uppercase animated slideInLeft"
                                            href="{{slide.buttonLink}}"
                                            style="animation-delay: 1.5s; opacity: 1;">{{slide.buttonText}}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            
        </div><a  href="#carouselExampleControls" role="button" data-bs-slide="prev"
            class="carousel-control-prev"><i  class="ion-chevron-left"></i></a><a
             href="#carouselExampleControls" role="button" data-bs-slide="next"
            class="carousel-control-next"><i  class="ion-chevron-right"></i></a>
    </div>
</div>
<div  class="main_content">
    <div  class="section pb_20">
        <div  class="container">
            <div  class="row">
                {% for collection in collections %}
                <div  class="col-md-6">
                    <div  class="single_banner"><img 
                            alt="shop_banner_img1"
                            src="/assets/images/collections/{{collection.imageUrl}}">
                        <div  class="single_banner_info">
                            <h5  class="single_bn_title1">{{collection.description}}</h5>
                            <h3  class="single_bn_title">{{collection.title}}</h3><a
                                 class="single_bn_link"
                                 target="_blank"
                                href="{{collection.buttonLink}}">{{collection.buttonText}}</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div  class="section small_pt pb_70">
        <div  class="container">
            <div  class="row justify-content-center">
                <div  class="col-md-6">
                    <div  class="heading_s1 text-center">
                        <h2 >Exclusive Products</h2>
                    </div>
                </div>
            </div>
            <div  class="row">
                <div  class="col-12">
                    <div  class="tab-style1">
                        <ul  role="tablist" class="nav nav-tabs justify-content-center">
                            <li  class="nav-item"><a 
                                    id="arrival-tab" data-bs-toggle="tab" href="#arrival" role="tab"
                                    aria-controls="arrival" aria-selected="true" class="nav-link active">New
                                    Arrival</a></li>
                            <li  class="nav-item"><a 
                                    id="sellers-tab" data-bs-toggle="tab" href="#sellers" role="tab"
                                    aria-controls="sellers" aria-selected="false" class="nav-link">Best Sellers</a>
                            </li>
                            <li  class="nav-item"><a 
                                    id="featured-tab" data-bs-toggle="tab" href="#featured" role="tab"
                                    aria-controls="featured" aria-selected="false" class="nav-link">Featured</a>
                            </li>
                            <li  class="nav-item"><a 
                                    id="special-tab" data-bs-toggle="tab" href="#special" role="tab"
                                    aria-controls="special" aria-selected="false" class="nav-link">Special Offer
                                </a></li>
                        </ul>
                    </div>
                    <div  class="tab-content">
                        <div  id="arrival" role="tabpanel" aria-labelledby="arrival-tab"
                            class="tab-pane fade show active">
                            <div  class="row shop_container">
                                {% for product in productsNewArrival %}
                                    {% include "product/display_product.html.twig" %}
                                {% endfor %}
                            </div>
                        </div>
                        <div  id="sellers" role="tabpanel" aria-labelledby="sellers-tab"
                            class="tab-pane fade">
                            <div  class="row shop_container">
                                {% for product in productsBestSeller %}
                                    {% include "product/display_product.html.twig" %}
                                {% endfor %}
                            </div>
                        </div>
                        <div  id="featured" role="tabpanel"
                            aria-labelledby="featured-tab" class="tab-pane fade">
                            <div  class="row shop_container">
                                {% for product in productsFeatured %}
                                    {% include "product/display_product.html.twig" %}
                                {% endfor %}
                            </div>
                        </div>
                        <div  id="special" role="tabpanel" aria-labelledby="special-tab"
                            class="tab-pane fade">
                            <div  class="row shop_container">
                                {% for product in productsSpecialOffer %}
                                    {% include "product/display_product.html.twig" %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}