src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use App\Entity\Category;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $more_description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $additional_infos = null;

    #[ORM\Column(nullable: true)]
    private ?int $stock = null;

    #[ORM\Column]
    private ?int $solde_price = null;

    #[ORM\Column]
    private ?int $regular_price = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'products')]
    private Collection $categories;

    #[ORM\Column(type: Types::ARRAY)]
    private array $imageUrls = [];

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $brand = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isAvailable = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isBestSeller = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isNewArrival = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isFeatured = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isSpecialOffer = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(targetEntity: self::class)]
    private ?self $relatedProducts = null;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->relatedProducts = new ArrayCollection();
        $this->setCreatedAt( new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;
        $this->setSlug((new Slugify())->slugify ($name));
        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getMoreDescription(): ?string
    {
        return $this->more_description;
    }

    public function setMoreDescription(?string $more_description): static
    {
        $this->more_description = $more_description;

        return $this;
    }

    public function getAdditionalInfos(): ?string
    {
        return $this->additional_infos;
    }

    public function setAdditionalInfos(?string $additional_infos): static
    {
        $this->additional_infos = $additional_infos;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getSoldePrice(): ?int
    {
        return $this->solde_price;
    }

    public function setSoldePrice(int $solde_price): static
    {
        $this->solde_price = $solde_price;

        return $this;
    }

    public function getRegularPrice(): ?int
    {
        return $this->regular_price;
    }

    public function setRegularPrice(int $regular_price): static
    {
        $this->regular_price = $regular_price;

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getImageUrls(): array
    {
        return $this->imageUrls;
    }

    public function setImageUrls(array $imageUrls): static
    {
        $this->imageUrls = $imageUrls;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(?string $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function isIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(?bool $isAvailable): static
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    public function isIsBestSeller(): ?bool
    {
        return $this->isBestSeller;
    }

    public function setIsBestSeller(?bool $isBestSeller): static
    {
        $this->isBestSeller = $isBestSeller;

        return $this;
    }

    public function isIsNewArrival(): ?bool
    {
        return $this->isNewArrival;
    }

    public function setIsNewArrival(?bool $isNewArrival): static
    {
        $this->isNewArrival = $isNewArrival;

        return $this;
    }

    public function isIsFeatured(): ?bool
    {
        return $this->isFeatured;
    }

    public function setIsFeatured(?bool $isFeatured): static
    {
        $this->isFeatured = $isFeatured;

        return $this;
    }

    public function isIsSpecialOffer(): ?bool
    {
        return $this->isSpecialOffer;
    }

    public function setIsSpecialOffer(?bool $isSpecialOffer): static
    {
        $this->isSpecialOffer = $isSpecialOffer;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getRelatedProducts(): ?self
    {
        return $this->relatedProducts;
    }

    public function setRelatedProducts(?self $relatedProducts): static
    {
        $this->relatedProducts = $relatedProducts;

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }
}

templates/product/display_product.html.twig
<div  class="col-lg-3 col-md-4 col-6">
                                    <div  class="product">
                                        <div  class="product_img"><a
                                                 href="/product/{{product.slug}}"><img
                                                     alt="product_img1"
                                                    src="/assets/images/products/{{product.imageUrls[0]}}"></a>
                                            <div  class="product_action_box">
                                                <ul  class="list_none pr_action_btn">
                                                    <li  class="add-to-cart">
                                                        <a href="/cart/add/{{product.id}}/1">
                                                            <i class="icon-basket-loaded"></i> 
                                                            Add To Cart 
                                                        </a>
                                                    </li>
                                                    <li >
                                                        <a href="/compare/add/{{product.id}}" class="add-to-compare">
                                                            <i class="icon-shuffle"></i>
                                                        </a>
                                                    </li>
                                                    <li>
                                                        <a href="shop-quick-view.html" class="popup-ajax">
                                                            <i class="icon-magnifier-add"></i>
                                                        </a>
                                                    </li>
                                                    <li >
                                                        <a href="#"><i class="icon-heart"></i></a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div  class="product_info">
                                            <h6  class="product_title">
                                                <a href="/product/{{product.slug}}">
                                                    {{product.name}}
                                                </a>
                                            </h6>
                                            <div  class="product_price">
                                                <span class="price">{{(product.soldePrice/100) | format_currency('EUR')}}</span>
                                                <del>{{(product.regularPrice/100) | format_currency('EUR')}}</del>
                                                <div  class="on_sale">
                                                    <span>{{((product.regularPrice - product.soldePrice)*100/product.regularPrice)| number_format(2, ',', '.')}}% Off</span>
                                                </div>
                                            </div>
                                            <div  class="rating_wrap">
                                                <div  class="rating">
                                                    <div  class="product_rate"
                                                        style="width: 80%;"></div>
                                                </div><span 
                                                    class="rating_num">(21)</span>
                                            </div>
                                            <div  class="pr_desc">
                                                <p >Lorem ipsum dolor sit amet,
                                                    consectetur adipiscing elit. Phasellus blandit massa enim.
                                                    Nullam id varius nunc id varius nunc.</p>
                                            </div>
                                            <div  class="pr_switch_wrap">
                                                <div  class="product_color_switch"><span
                                                         data-color="#87554B"
                                                        class="active"></span><span 
                                                        data-color="#333333"></span><span
                                                         data-color="#DA323F"></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>